// pluginの読み込み。apply pluginではなく plugin DSLを使って書かれている
plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
	id 'com.google.cloud.tools.jib' version '3.5.2'
}

// ビルドの情報。
group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'spring boot sandbox application'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

// リポジトリの設定。外部ライブラリを利用する場合はどこからそれをダウンロードしてくるかの設定が必要
// 今回はmavanが管理しているリポジトリを利用している
repositories {
	mavenCentral()
}

// 外部ライブラリの読み込み。dependenciesブロック内にパッケージ名トライブラリ名を記載する
// implementationは全パッケージで、testImplementationはtest配下のパッケージで利用できる
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// OpenTelemetryを利用するために追加
	implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
	implementation 'am.ik.spring.opentelemetry:otel-logs-autoconfigure:0.6.0'
	
	// compileOnly:実行する時には要らないけど、コンパイル時には必要
	compileOnly 'org.projectlombok:lombok'
	
	// developmentOnly:開発環境でのみ必要。本番環境ではこれで指定した依存関係は含まれない
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

// もともと存在する「test」というタスクを拡張している
// org.springframework.boot:spring-boot-starter-testを入れると、useJUnitPlatform()というメソッドが利用できるようになる
// useJUnitPlatform()はjUnit5で実行するよという意味
tasks.named('test') {
	useJUnitPlatform()
}

jib {
	from {
		image = "paketobuildpacks/ubuntu-noble-run-tiny:latest"
	}
    to {
        image = "sandbox-service-jib:${project.version}"
    }
}

tasks.named("bootBuildImage") {
    imageName = "sandbox-service-gradle-buildpacks:${project.version}"
}
